{{- if .Values.replicaSet.enabled -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" $ }}-init
  labels:
    app: {{ template "fullname" $ }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "argocd.argoproj.io/hook": Sync
    "argocd.argoproj.io/sync-wave": "2"
spec:
  backoffLimit: 1
  template:
    metadata:
      annotations:
    spec:
      containers:
      - name: {{ template "fullname" $ }}-init-replicaset
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        command:
          - /bin/bash
        args:
          - -c
          - |
            #!/bin/bash
            set -euo pipefail;
            HEADLESS_SVC="{{ template "fullname" $ }}";
            MASTER_NODE="{{ template "fullname" $ }}-0.$HEADLESS_SVC";
            AUTH_DATA="{{ .Values.auth.rootUser }}:$MONGO_INITDB_ROOT_PASSWORD";
            CONNECT_STRING_MASTER="mongodb://$AUTH_DATA@$MASTER_NODE/admin";

            DB_PING_CMD='db.runCommand({ping: 1})';
            RS_CHECK_CMD='rs.status()';
            RS_INIT_CMD='rs.initiate({
              _id: "{{ .Values.replicaSet.name }}",
              members: [
                {{- $name := include "fullname" $ -}}
                {{- $replicas := .Values.replicaCount | int -}}
                {{- range $i, $_ := until $replicas }}
                  { _id: {{ $i }}, host: "{{ $name }}-{{ $i }}.{{ $name }}:27017" }{{- if lt (add1 $i) $replicas }},{{ end }}
                {{- end }}
              ]
            })';

            SLEEP_TIME='2';

            until mongosh "$CONNECT_STRING_MASTER" --eval "$DB_PING_CMD" > /dev/null; do
                echo "Waiting master to become ready, sleeping $SLEEP_TIME s..";
                sleep "$SLEEP_TIME";
            done

            if ! mongosh "$CONNECT_STRING_MASTER" --eval "$RS_CHECK_CMD" > /dev/null; then
                echo "Initializing replicaset..";
                mongosh "$CONNECT_STRING_MASTER" --eval "$RS_INIT_CMD" > /dev/null;
            fi
        env:
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" $ }}-auth
                key: root-password
      restartPolicy: Never
{{- end -}}
