{{- $replicas := .Values.replicaCount | int -}}
{{- range $i, $_ := until $replicas }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" $ }}-{{ $i }}
  labels:
    app: {{ template "fullname" $ }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    "argocd.argoproj.io/hook": Sync
    "argocd.argoproj.io/sync-wave": "-5"
spec:
  type: {{ $.Values.service.type }}
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  selector:
    statefulset.kubernetes.io/pod-name: {{ template "fullname" $ }}-{{ $i }}
---
{{- end }}
