{{- if .Values.replicaSet.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-keyfile
  namespace: {{ .Release.Namespace }}
  {{- if and .Values.vault.enabled .Values.replicaSet.keyVault }}
  annotations:
    vault.security.banzaicloud.io/vault-addr: {{ .Values.vault.address | quote }}
    vault.security.banzaicloud.io/vault-path: {{ .Values.vault.path | quote }}
  {{- end }}
type: Opaque
{{- if and .Values.vault.enabled .Values.replicaSet.keyVault }}
stringData:
  key: {{ .Values.replicaSet.keyVault }}
{{- else }}
data:
  key: {{ .Values.replicaSet.key | b64enc | quote }}
{{- end }}
{{- end -}}
