{{- if .Values.auth.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" $ }}-auth
  namespace: {{ .Release.Namespace }}
  {{- if and .Values.vault.enabled .Values.auth.rootPasswordVault }}
  annotations:
    vault.security.banzaicloud.io/vault-addr: {{ .Values.vault.address | quote }}
    vault.security.banzaicloud.io/vault-path: {{ .Values.vault.path | quote }}
  {{- end }}
type: Opaque
{{- if and .Values.vault.enabled .Values.auth.rootPasswordVault }}
stringData:
  root-password: {{ .Values.auth.rootPasswordVault }}
{{- else }}
data:
  root-password: {{ .Values.auth.rootPassword | b64enc | quote }}
{{- end }}
{{- end }}
