apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  clusterIP: None
  ports:
    - port: 27017
      name: mongo
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}

