{{- if and (.Values.vault).enabled ((.Values.vault).service_account).create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.vault.service_account.name | default "vault" }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
