apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  root-password: {{ .Values.auth.rootPassword | b64enc | quote }}

